/** Pools of realistic project-management content. No "Demo Task N" names. */

export const TASK_TITLES = [
  "Implement authentication flow",
  "Review mobile navigation",
  "Fix dashboard loading state",
  "Design onboarding experience",
  "Optimize project query",
  "Add task filtering",
  "Prepare release notes",
  "Investigate notification issue",
  "Create analytics empty state",
  "Refactor task status mutation",
  "Set up CI pipeline",
  "Write onboarding documentation",
  "Fix avatar upload edge case",
  "Improve board drag performance",
  "Add due-date reminders",
  "Audit team permissions",
  "Migrate legacy settings page",
  "Design billing upgrade flow",
  "Fix timezone display bug",
  "Add keyboard shortcuts to board",
  "Review pull request backlog",
  "Update empty-state illustrations",
  "Harden invitation token flow",
  "Add project progress indicators",
  "Fix comment thread ordering",
  "Design dark-mode palette pass",
  "Reduce bundle size on tasks page",
  "Add search across projects",
  "Write API error-handling guide",
  "Fix flaky date formatting test",
  "Plan quarterly roadmap",
  "Interview support-tool vendors",
  "Clean up dead feature flags",
  "Add audit log export",
  "Fix session expiry redirect loop",
  "Design team invitation email",
  "Benchmark task list rendering",
  "Add bulk task actions",
  "Review accessibility of dialogs",
  "Document release process",
  "Fix pagination off-by-one",
  "Add workspace usage metrics",
  "Design profile contribution view",
  "Investigate slow board load",
  "Add comment mentions",
  "Fix label color contrast",
  "Prepare security review notes",
  "Add project archiving",
  "Design mobile task detail",
  "Fix notification badge count",
  "Write data-retention policy draft",
  "Add SSO provider mapping",
  "Review error-toast copy",
  "Optimize avatar image sizes",
  "Add task templates",
  "Fix overlapping dropdown menus",
  "Design activity feed",
  "Load-test comment endpoints",
  "Add export to CSV",
  "Fix stale sidebar badge",
];

export const TASK_DESCRIPTIONS = [
  "Break this into smaller steps before starting implementation.",
  "Check with the team during standup before picking this up.",
  "Customer-reported; reproduce locally first.",
  "Depends on the API change landing first.",
  "Keep the change small and well-tested.",
  "Draft is in the shared doc; needs a second pair of eyes.",
  "Performance-sensitive area, measure before and after.",
  "Edge cases around empty states need coverage.",
  "Follow up with design on the final copy.",
  "Should be safe to roll out behind the existing flag.",
];

export const TASK_COMMENTS = [
  "Started investigating this.",
  "Looks good, I'll take the API portion.",
  "Blocked by the authentication change.",
  "Ready for review.",
  "Fixed in the latest commit.",
  "Can reproduce locally, digging in.",
  "Left some notes in the description.",
  "This will need a migration; flagging early.",
  "Verified on staging.",
  "Splitting this into two smaller tasks.",
  "Waiting on design feedback.",
  "Pushed a first pass, feedback welcome.",
];
