version: "3.8"

services:
  postgres:
    image: postgres
    container_name: my-local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local_dev_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
